notes: Pairwise comparison without replicates with default parameter setting.

data:
        KO:
                rep1: /home/colorectalCA/Modification/xPore/T1/xPore/data/Texp/dataprep
                rep2: /home/colorectalCA/Modification/xPore/T2/xPore/data/Texp/dataprep
                rep3: /home/colorectalCA/Modification/xPore/T3/xPore/data/Texp/dataprep
                rep4: /home/colorectalCA/Modification/xPore/T4/xPore/data/Texp/dataprep
                rep5: /home/colorectalCA/Modification/xPore/T5/xPore/data/Texp/dataprep
        WT:
                rep1: /home/colorectalCA/Modification/xPore/N1/xPore/data/Control/dataprep
                rep2: /home/colorectalCA/Modification/xPore/N2/xPore/data/Control/dataprep
                rep3: /home/colorectalCA/Modification/xPore/N3/xPore/data/Control/dataprep
                rep4: /home/colorectalCA/Modification/xPore/N4/xPore/data/Control/dataprep
                rep5: /home/colorectalCA/Modification/xPore/N5/xPore/data/Control/dataprep

out: /home/colorectalCA/Modification/xPore/Five_rep_output



criteria:
    readcount_min: 2
    readcount_max: 1000

method:
    prefiltering:
        method: t-test
        threshold: 0.05
